version: '2'

services:
  web:
    build: ./docker/cake
    network_mode: "bridge"
    links:
      - db
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/php_additional.ini:/usr/local/etc/php/conf.d/php_additional.ini

  db:
    image: mysql:5.6
    network_mode: "bridge"
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: aperophp

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    network_mode: "bridge"
    links:
      - db
    ports:
      - "8081:80"

  composer:
    image: composer:latest
    network_mode: "bridge"
    links:
      - db
    volumes:
      - $HOME/.composer:/composer
      - ./:/var/www
    working_dir: /var/www

volumes:
  db_data: